const mongoose = require("mongoose");

const documentSchema = new mongoose.Schema({
    loanId: { type: String , unique: true},
    aadharImageFront: { type: String },
    aadharImageBack: { type: String },
    aadharNumber :{ type: String },
    panImage: { type: String},
    panNumber: { type: String },
    profilePic: { type: String },
    chassisImage: { type: String },
    chassisNumber: { type: String },
    motorImage: { type: String },
    motorNumber: { type: String },
    batteryImage: { type: String },
    batterySerialNumber: { type: String },
    passbookImage: { type: String },
    accountNumber: { type: String },
    customerWithVehicleImage: { type: String },
    customerWithVehicleDesc: { type: String },
    invoiceImage: { type: String },
    invoiceNumber: { type: String },
    manufacturingYear: { type: String },
    vehicleUsageType: { type: String },
    rtoCode: { type: String },
    exShowroomPrice: { type: String },
    downPayment: { type: String },
    rtoCharge: { type: String },
    otherCharge: { type: String },
    onRoadPrice: { type: String },
    description: { type: String },
    nachImage: { type: String },
    nachDescription : { type: String },
    insuranceImage: { type: String },
    insurancePolicyNumber: { type: String },
    vehicleDispatchIDImage: { type: String },
    vehicleDispatchIDNumber: { type: String },
    rcUploadImage: { type: String },
    rcUploadNumber: { type: String },
  },
);

module.exports = mongoose.model("Document", documentSchema);
